### ISSUE TITLE
Hrv data is not available, but you can see this data in the hrvFiveMinuteData class

### ISSUE THREAD

**Issue by jy151** [HBandSDK/Android_Ble_SDK#15]
Hrv data is not available, but you can see this data in the hrvFiveMinuteData class

**Comment by jy151** [comment]
![image](https://github.com/HBandSDK/Android_Ble_SDK/assets/104863764/3f8b91f2-79b6-4d35-9b5f-8a475582c9d0)
这里是可以看到HRV的但是我无论是用VPOperateManager.getInstance().readOriginData还是readHRVOrigin都是读取不到的

**Comment by innomesOfficial** [comment]
I'm having the same problem.
Did you solve it?
