### ISSUE TITLE
SDK language urgent issue!!!

### ISSUE THREAD

**Issue by arnavdots** [HBandSDK/Android_Ble_SDK#2]
Hello there,

I have a requirement where I need to use the SDK but my native language is English and won't able to understand the SDK flow as all the commenting and application labels are in Chinese.

**Comment by TimAimee** [comment]
> Hello there,
> 
> I have a requirement where I need to use the SDK but my native language is English and won't able to understand the SDK flow as all the commenting and application labels are in Chinese.

the doc api is chinese,but the readme is english.

https://github.com/HBandSDK/Android_Ble_SDK/blob/master/README_EN.md

**Comment by kov-serg** [comment]
I've done translation using google translate.
